{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "microservice.fullname" . }}-restrictive
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  # Allow traffic only from current namespace or ingress controller pods
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  # Allow Egress to local DNS resolvers and external APIs
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
